### ISSUE TITLE
Use ctru_sys to provide libctru functions/types/values

### ISSUE THREAD

**Issue by AzureMarker** [Meziu/pthread-3ds#7]
Like https://github.com/Meziu/rust-linker-fix-3ds, we can depend on https://github.com/Meziu/ctru-rs so we don't duplicate these definitions.

**Comment by Meziu** [comment]
Fixed in https://github.com/Meziu/pthread-3ds/commit/87eceaf5ef07e6f191b4f2373b7a647f49dc6e82
